services:
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - ui
    volumes:
      - ui-build:/usr/share/nginx/html
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ui-build:/app/build

volumes:
  ui-build:
